using System.Text.Json.Serialization;

namespace FaultResponseSystem.Models;

/// <summary>
/// Fault types detected by the anomaly detector, mapped to common BMS failure modes.
/// </summary>
[JsonConverter(typeof(JsonStringEnumConverter))]
public enum FaultType
{
    Spike,      // Sudden abnormal reading
    Drift,      // Gradual deviation from baseline
    Flatline,   // Sensor stuck at one value
    Missing,    // No data received
    Oscillation // Rapid cycling between values
}

/// <summary>
/// Types of energy meters from BDG2 dataset.
/// </summary>
[JsonConverter(typeof(JsonStringEnumConverter))]
public enum MeterType
{
    Electricity,
    ChilledWater,
    Steam,
    HotWater,
    Irrigation
}

/// <summary>
/// A detected fault alert generated by the AnomalyDetector from BDG2 meter readings.
/// This is the primary input to the agent DAG.
/// </summary>
public class Alert
{
    public string AlertId { get; set; } = string.Empty;
    public string MeterId { get; set; } = string.Empty;
    public string BuildingId { get; set; } = string.Empty;
    public string SiteId { get; set; } = string.Empty;
    public DateTime Timestamp { get; set; }
    public MeterType MeterType { get; set; }
    public FaultType FaultType { get; set; }
    public double AnomalousValue { get; set; }
    public double ExpectedMin { get; set; }
    public double ExpectedMax { get; set; }
    public double DeviationScore { get; set; } // Z-score or anomaly magnitude
    public string Description { get; set; } = string.Empty;
}
